export const USER_FORM_USERNAME_LOGIN = "USER_FORM_USERNAME_LOGIN";
export const USER_FORM_PASSWORD_LOGIN = "USER_FORM_PASSWORD_LOGIN";
export const USER_FORM_CAPTCHA_LOGIN = "USER_FORM_CAPTCHA_LOGIN";
